# The URL the site will be built for
base_url = "https://dineau.github.io"
generate_rss = true
compile_sass = true

title = "DinEau Photography"
description = "Capturing Special Stories"

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[extra]
author = "DinEau"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/contact", name = "Contact"}
]
clean_blog_social = [
    {url = "https://twitter.com", icon="fab fa-twitter"},
    {url = "$BASE_URL/rss.xml", icon="fas fa-rss"}
]
