name: Github Pages Release
run-name: ${{ github.actor }} released a new version of the website
on: [push]
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        name: Checkout main
      - uses: actions/checkout@main
        name: Checkout gh-pages
        with: 
          ref: "gh-pages"
      - run: git checkout main -- .
      - uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build website and recreate docs pages
        id: vars
        run: nix run
      - name: Commit the changes to gh pages
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Website Build Bot
          author_email: web-build@site.bot
